spring:
  application:
    name: service_player_1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8093
server:
  port: 8093
