eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    service-car-0: /svc/car/0/**
    service_player_0: /svc/player/0/**

